// frontend/src/pages/TeacherDashboard.tsx
import { useState, useEffect, useCallback } from "react";
import { Menu } from "lucide-react";
import StarBackground from "../components/StarBackground";
import ViewTimetable from "./ViewTimetable";
import authService from "../services/auth.service";
import { toast } from "sonner";

const TeacherDashboard = () => {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [activePage, setActivePage] = useState("dashboard");
  const [teacherName, setTeacherName] = useState("");
  const user = authService.getCurrentUser();

  useEffect(() => {
    if (user) {
      setTeacherName(user.full_name || user.username);
    }
  }, [user]);

  const renderPage = () => {
    switch(activePage) {
      case "view-timetable":
        return <ViewTimetable />;
      default:
        return (
          <div className="space-y-6">
            <div className="bg-card/60 backdrop-blur-md rounded-xl p-8 border border-border">
              <h2 className="text-2xl font-bold mb-4">👋 Welcome {teacherName || "Teacher"}</h2>
              <p className="text-muted-foreground">View and manage your class schedules and timetables.</p>
              <p className="text-muted-foreground mt-2">Timetables are generated by the admin and automatically shared with all teachers and students.</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              <div className="bg-card/60 backdrop-blur-md rounded-xl p-6 border border-border cursor-pointer hover:border-primary/50 transition-all" onClick={() => setActivePage("view-timetable")}>
                <div className="text-4xl mb-3">👁️</div>
                <h3 className="text-lg font-bold">View Timetable</h3>
                <p className="text-sm text-muted-foreground">See class schedules for all sections</p>
              </div>
              <div className="bg-card/60 backdrop-blur-md rounded-xl p-6 border border-border cursor-pointer hover:border-primary/50 transition-all" onClick={() => toast.info("Select a section to view your schedule")}>
                <div className="text-4xl mb-3">📅</div>
                <h3 className="text-lg font-bold">My Schedule</h3>
                <p className="text-sm text-muted-foreground">View your personal teaching schedule</p>
              </div>
              <div className="bg-card/60 backdrop-blur-md rounded-xl p-6 border border-border cursor-pointer hover:border-primary/50 transition-all" onClick={() => toast.info("Room allocations are shown in the timetable")}>
                <div className="text-4xl mb-3">🏫</div>
                <h3 className="text-lg font-bold">Room Assignments</h3>
                <p className="text-sm text-muted-foreground">Check classroom allocations</p>
              </div>
            </div>
          </div>
        );
    }
  };

  return (
    <div className="min-h-screen relative">
      <StarBackground />

      <div className="relative z-10">
        <header className="sticky top-0 z-30 border-b border-border bg-background/40 backdrop-blur-xl px-6 py-4">
          <div className="flex items-center gap-4">
            <button onClick={() => setSidebarOpen(true)} className="lg:hidden text-foreground">
              <Menu size={24} />
            </button>
            <div>
              <h1 className="text-2xl font-bold flex items-center gap-2">
                👨‍🏫 <span>Teacher Dashboard</span>
              </h1>
              <p className="text-sm text-muted-foreground">Welcome, {user?.full_name || user?.username}!</p>
            </div>
          </div>
        </header>

        <main className="p-6">
          {renderPage()}
        </main>
      </div>
    </div>
  );
};

export default TeacherDashboard;